import { and, eq, gt, inArray, lt, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { coopActions, coopSessions } from "../../../db/schema";

const allowed=new Set(["pulse","interact","medkit","drone","shield","vent"]);

// No Cron Trigger is available on this hosting setup, so stale sessions (and their
// actions) are swept opportunistically whenever a new session is created.
async function cleanupStaleSessions(db:Awaited<ReturnType<typeof getDb>>){const stale=await db.select({code:coopSessions.code}).from(coopSessions).where(lt(coopSessions.updatedAt,sql`datetime('now','-3 hours')`));if(!stale.length)return;const codes=stale.map(row=>row.code);await db.delete(coopActions).where(inArray(coopActions.code,codes));await db.delete(coopSessions).where(inArray(coopSessions.code,codes));}

export async function GET(request:Request){try{const url=new URL(request.url),code=(url.searchParams.get("code")??"").toUpperCase().slice(0,6),after=Math.max(0,Number(url.searchParams.get("after"))||0);if(!code)return Response.json({error:"code is required"},{status:400});const db=await getDb(),session=await db.select().from(coopSessions).where(eq(coopSessions.code,code)).get();if(!session)return Response.json({error:"session not found"},{status:404});const actions=await db.select().from(coopActions).where(and(eq(coopActions.code,code),gt(coopActions.id,after))).orderBy(coopActions.id).limit(20);return Response.json({connected:session.connected,actions});}catch{return Response.json({error:"협동 세션을 불러오지 못했습니다."},{status:500});}}

export async function POST(request:Request){try{const payload=await request.json() as {op?:string;code?:string;action?:string},code=(payload.code??"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(!code)return Response.json({error:"code is required"},{status:400});const db=await getDb();if(payload.op==="create"){await cleanupStaleSessions(db);await db.insert(coopSessions).values({code,connected:false,updatedAt:sql`CURRENT_TIMESTAMP`}).onConflictDoUpdate({target:coopSessions.code,set:{connected:false,updatedAt:sql`CURRENT_TIMESTAMP`}});await db.delete(coopActions).where(eq(coopActions.code,code));return Response.json({code});}if(payload.op==="connect"){const session=await db.select().from(coopSessions).where(eq(coopSessions.code,code)).get();if(!session)return Response.json({error:"session not found"},{status:404});await db.update(coopSessions).set({connected:true,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(coopSessions.code,code));return Response.json({connected:true});}if(payload.op==="action"&&payload.action&&allowed.has(payload.action)){const session=await db.select().from(coopSessions).where(eq(coopSessions.code,code)).get();if(!session)return Response.json({error:"session not found"},{status:404});const [action]=await db.insert(coopActions).values({code,action:payload.action}).returning();await db.update(coopSessions).set({connected:true,updatedAt:sql`CURRENT_TIMESTAMP`}).where(eq(coopSessions.code,code));return Response.json({action},{status:201});}return Response.json({error:"invalid operation"},{status:400});}catch{return Response.json({error:"협동 입력을 전송하지 못했습니다."},{status:500});}}
