import { desc, eq, sql } from "drizzle-orm";
import { getDb } from "../../../db";
import { keeperProfiles, missionReports } from "../../../db/schema";
import { clampReport, sanitizeDifficulty, sanitizeScenarioId } from "../../../db/mission-scoring";

const emptyProfile={xp:0,streak:0,missions:0,bestIndex:0,badges:[] as string[],sensorLevel:1,suitTier:1};

function profileView(row:typeof keeperProfiles.$inferSelect|undefined){if(!row)return emptyProfile;let badges:string[]=[];try{badges=JSON.parse(row.badges) as string[];}catch{}return{xp:row.xp,streak:row.streak,missions:row.missions,bestIndex:row.bestIndex,badges,sensorLevel:row.sensorLevel,suitTier:row.suitTier};}
function routeError(error:unknown){const message=error instanceof Error?error.message:"데이터 처리 중 오류가 발생했습니다.";return message.includes("no such table")?"학습 기록 데이터베이스를 준비하는 중입니다.":message;}

export async function GET(request:Request){try{const profileId=new URL(request.url).searchParams.get("profileId")?.slice(0,90)??"";if(!profileId)return Response.json({error:"profileId is required"},{status:400});const db=await getDb();const reports=await db.select().from(missionReports).where(eq(missionReports.profileId,profileId)).orderBy(desc(missionReports.id)).limit(200);const profile=await db.select().from(keeperProfiles).where(eq(keeperProfiles.profileId,profileId)).get();return Response.json({reports:reports.map(item=>{const output:Partial<typeof item>={...item};delete output.profileId;return output;}),profile:profileView(profile)});}catch(error){return Response.json({error:routeError(error)},{status:500});}}

export async function POST(request:Request){try{const payload=await request.json() as {profileId?:string;report?:Record<string,unknown>},profileId=payload.profileId?.slice(0,90)??"",rawReport=payload.report;if(!profileId||!rawReport)return Response.json({error:"invalid report"},{status:400});const db=await getDb();const current=await db.select().from(keeperProfiles).where(eq(keeperProfiles.profileId,profileId)).get();const difficulty=sanitizeDifficulty(rawReport.difficulty),scenarioId=sanitizeScenarioId(rawReport.scenarioId),report=clampReport(rawReport,difficulty),safetyIndex=report.safetyIndex,victory=report.victory,oldBadges=profileView(current).badges,badges=new Set(oldBadges);if(victory)badges.add("첫 봉인");if(safetyIndex>=90)badges.add("골든타임 마스터");if(report.rescued>=2)badges.add("구조 수호자");if(report.sparkHits===0)badges.add("무점화 완수");if(Number(rawReport.maxCombo)>=5)badges.add("SAFE 콤보 마스터");if(Boolean(rawReport.crisisSuccess))badges.add("5초 골든 세이브");badges.add(({kitchen:"LNG 배지",restaurant:"LPG 배지",camping:"부탄가스 배지",laboratory:"배관 분석 배지",boiler:"CO 배지"} as Record<string,string>)[scenarioId]??"가스안전 배지");const missions=(current?.missions??0)+1,xp=(current?.xp??0)+report.score+safetyIndex*4,streak=victory?(current?.streak??0)+1:0,bestIndex=Math.max(current?.bestIndex??0,safetyIndex),sensorLevel=Math.min(5,1+Math.floor(missions/2)+Math.floor(badges.size/4)),suitTier=Math.min(4,1+Math.floor(xp/2600));await db.insert(keeperProfiles).values({profileId,xp,streak,missions,bestIndex,badges:JSON.stringify([...badges]),sensorLevel,suitTier,updatedAt:sql`CURRENT_TIMESTAMP`}).onConflictDoUpdate({target:keeperProfiles.profileId,set:{xp,streak,missions,bestIndex,badges:JSON.stringify([...badges]),sensorLevel,suitTier,updatedAt:sql`CURRENT_TIMESTAMP`}});const [saved]=await db.insert(missionReports).values({profileId,victory:report.victory,score:report.score,timeUsed:report.timeUsed,hp:report.hp,seals:report.seals,defeated:report.defeated,knowledge:report.knowledge,rescued:report.rescued,scenarioId,difficulty,safetyJudgment:report.safetyJudgment,goldenTime:report.goldenTime,rescueScore:report.rescueScore,knowledgeScore:report.knowledgeScore,safetyIndex,wrongChoices:report.wrongChoices,sparkHits:report.sparkHits,gasExposure:report.gasExposure,pulseCount:report.pulseCount,lastMistake:report.lastMistake,coopActions:report.coopActions}).returning();const publicReport:Partial<typeof saved>={...saved};delete publicReport.profileId;return Response.json({report:publicReport,profile:{xp,streak,missions,bestIndex,badges:[...badges],sensorLevel,suitTier}},{status:201});}catch(error){return Response.json({error:routeError(error)},{status:500});}}

export async function DELETE(request:Request){try{const profileId=new URL(request.url).searchParams.get("profileId")?.slice(0,90)??"";if(!profileId)return Response.json({error:"profileId is required"},{status:400});const db=await getDb();await db.batch([db.delete(missionReports).where(eq(missionReports.profileId,profileId)),db.delete(keeperProfiles).where(eq(keeperProfiles.profileId,profileId))]);return Response.json({ok:true});}catch(error){return Response.json({error:routeError(error)},{status:500});}}
